'use strict';

// tests for currentTime
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('currentTime', '/handler.js', 'endpoint');

describe('currentTime', () => {
  before((done) => {
    done();
  });

  it('should return current time', async () => {
    const response = await wrapped.run({});
    expect(response).to.have.property("statusCode", 200);
    expect(response).to.have.property('body').and.match(/.*\s\d{2}:\d{2}:\d{2}\sGMT(\+|-){1}\d{4}\s\(.*\)\./)
  });
});
